/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package isi.deso.tpdsw.Views;

import javax.swing.*;

/**
 *
 * @author kevin
 */
public class ClienteJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClienteJPanel
     */
    public ClienteJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClienteJPanel = new javax.swing.JPanel();
        ListaClienteJPanel = new javax.swing.JPanel();
        ClienteTitleTextField = new javax.swing.JTextField();
        buscadorTextField1 = new javax.swing.JTextField();
        buscadorJLabel1 = new javax.swing.JLabel();
        btnCrear1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        clientesJTable = new javax.swing.JTable();

        ClienteTitleTextField.setBackground(new java.awt.Color(255, 0, 0));
        ClienteTitleTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ClienteTitleTextField.setText("Lista de Clientes");
        ClienteTitleTextField.setFocusable(false);
        ClienteTitleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteTitleTextFieldActionPerformed(evt);
            }
        });

        buscadorJLabel1.setText("Buscador:");

        btnCrear1.setText("Crear Nuevo Cliente");
        btnCrear1.setToolTipText("");
        btnCrear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrear1ActionPerformed(evt);
            }
        });

        clientesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Dirección", "Cuit", "Direccion", "Pedidos", "Acciones"
            }
        ));
        clientesJTable.setRowHeight(30);
        jScrollPane2.setViewportView(clientesJTable);

        javax.swing.GroupLayout ListaClienteJPanelLayout = new javax.swing.GroupLayout(ListaClienteJPanel);
        ListaClienteJPanel.setLayout(ListaClienteJPanelLayout);
        ListaClienteJPanelLayout.setHorizontalGroup(
            ListaClienteJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListaClienteJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListaClienteJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
                    .addComponent(ClienteTitleTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ListaClienteJPanelLayout.createSequentialGroup()
                        .addComponent(btnCrear1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 547, Short.MAX_VALUE)
                        .addComponent(buscadorJLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(buscadorTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ListaClienteJPanelLayout.setVerticalGroup(
            ListaClienteJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaClienteJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ClienteTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ListaClienteJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscadorTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscadorJLabel1)
                    .addComponent(btnCrear1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout ClienteJPanelLayout = new javax.swing.GroupLayout(ClienteJPanel);
        ClienteJPanel.setLayout(ClienteJPanelLayout);
        ClienteJPanelLayout.setHorizontalGroup(
            ClienteJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 914, Short.MAX_VALUE)
            .addGroup(ClienteJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ListaClienteJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ClienteJPanelLayout.setVerticalGroup(
            ClienteJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGroup(ClienteJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ListaClienteJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 914, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ClienteJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ClienteJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ClienteTitleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteTitleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClienteTitleTextFieldActionPerformed

    private void btnCrear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrear1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ClienteJPanel;
    private javax.swing.JTextField ClienteTitleTextField;
    private javax.swing.JPanel ListaClienteJPanel;
    private javax.swing.JButton btnCrear1;
    private javax.swing.JLabel buscadorJLabel1;
    private javax.swing.JTextField buscadorTextField1;
    private javax.swing.JTable clientesJTable;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
   
    public JTable getJTable(){
        return this.clientesJTable;
    }
}
