/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package isi.deso.tpdsw.Views;

import javax.swing.JTable;

/**
 *
 * @author kevin
 */
public class ItemMenuJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ItemMenuJPanel
     */
    public ItemMenuJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ItemMenuJPanel = new javax.swing.JPanel();
        ListaPedidosPanel2 = new javax.swing.JPanel();
        ItemMenuTitleTextField = new javax.swing.JTextField();
        buscadorTextField2 = new javax.swing.JTextField();
        buscadorJLabel2 = new javax.swing.JLabel();
        btnCrearItemMenu = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        itemsMenuJTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(914, 542));

        ItemMenuJPanel.setPreferredSize(new java.awt.Dimension(914, 542));

        ItemMenuTitleTextField.setBackground(new java.awt.Color(255, 0, 0));
        ItemMenuTitleTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ItemMenuTitleTextField.setText("Lista de ItemsMenu");
        ItemMenuTitleTextField.setFocusable(false);
        ItemMenuTitleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemMenuTitleTextFieldActionPerformed(evt);
            }
        });

        buscadorJLabel2.setText("Buscador:");

        btnCrearItemMenu.setText("Crear Nuevo ItemMenu");
        btnCrearItemMenu.setToolTipText("");
        btnCrearItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearItemMenuActionPerformed(evt);
            }
        });

        itemsMenuJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Descripcion", "Precio", "Categoria", "AptoVegano", "Acciones"
            }
        ));
        itemsMenuJTable.setRowHeight(30);
        jScrollPane3.setViewportView(itemsMenuJTable);

        javax.swing.GroupLayout ListaPedidosPanel2Layout = new javax.swing.GroupLayout(ListaPedidosPanel2);
        ListaPedidosPanel2.setLayout(ListaPedidosPanel2Layout);
        ListaPedidosPanel2Layout.setHorizontalGroup(
            ListaPedidosPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaPedidosPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListaPedidosPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ItemMenuTitleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
                    .addGroup(ListaPedidosPanel2Layout.createSequentialGroup()
                        .addGroup(ListaPedidosPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ListaPedidosPanel2Layout.createSequentialGroup()
                                .addComponent(btnCrearItemMenu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buscadorJLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(buscadorTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ListaPedidosPanel2Layout.setVerticalGroup(
            ListaPedidosPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaPedidosPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ItemMenuTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ListaPedidosPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscadorTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscadorJLabel2)
                    .addComponent(btnCrearItemMenu))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout ItemMenuJPanelLayout = new javax.swing.GroupLayout(ItemMenuJPanel);
        ItemMenuJPanel.setLayout(ItemMenuJPanelLayout);
        ItemMenuJPanelLayout.setHorizontalGroup(
            ItemMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 914, Short.MAX_VALUE)
            .addGroup(ItemMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ItemMenuJPanelLayout.createSequentialGroup()
                    .addComponent(ListaPedidosPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );
        ItemMenuJPanelLayout.setVerticalGroup(
            ItemMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGroup(ItemMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ItemMenuJPanelLayout.createSequentialGroup()
                    .addComponent(ListaPedidosPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 914, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ItemMenuJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ItemMenuJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ItemMenuTitleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemMenuTitleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemMenuTitleTextFieldActionPerformed

    private void btnCrearItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearItemMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearItemMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ItemMenuJPanel;
    private javax.swing.JTextField ItemMenuTitleTextField;
    private javax.swing.JPanel ListaPedidosPanel2;
    private javax.swing.JButton btnCrearItemMenu;
    private javax.swing.JLabel buscadorJLabel2;
    private javax.swing.JTextField buscadorTextField2;
    private javax.swing.JTable itemsMenuJTable;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
    public JTable getJTable(){
        return this.itemsMenuJTable;
    }
}
