/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package isi.deso.tpdsw.Views;

import java.awt.CardLayout;
/**
 *
 * @author santi
 */
public class MenuJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuJFrame
     */
    public MenuJFrame() {
        initComponents();
        configurarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionJPanel = new javax.swing.JPanel();
        btnClientes = new javax.swing.JButton();
        btnVendedores = new javax.swing.JButton();
        btnItemsMenu = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        contenidoJPanel = new javax.swing.JPanel();
        VendedorJPanel = new javax.swing.JPanel();
        ListaVendedoresJPanel = new javax.swing.JPanel();
        VendedorTitleTextField = new javax.swing.JTextField();
        buscadorVendedorTextField = new javax.swing.JTextField();
        buscadorVendedorJLabel = new javax.swing.JLabel();
        btnCrearVendedor = new javax.swing.JButton();
        VendedorJScrollPane = new javax.swing.JScrollPane();
        vendedoresJTable = new javax.swing.JTable();
        ClienteJPanel = new javax.swing.JPanel();
        ListaClienteJPanel = new javax.swing.JPanel();
        ClienteTitleTextField = new javax.swing.JTextField();
        buscadorTextField1 = new javax.swing.JTextField();
        buscadorJLabel1 = new javax.swing.JLabel();
        btnCrear1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        clientesJTable = new javax.swing.JTable();
        ItemMenuJPanel = new javax.swing.JPanel();
        ListaPedidosPanel2 = new javax.swing.JPanel();
        ItemMenuTitleTextField = new javax.swing.JTextField();
        buscadorTextField2 = new javax.swing.JTextField();
        buscadorJLabel2 = new javax.swing.JLabel();
        btnCrearItemMenu = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        vendedoresJTable2 = new javax.swing.JTable();
        PedidoJPanel = new javax.swing.JPanel();
        ListaPedidosJPanle = new javax.swing.JPanel();
        TitleTextField3 = new javax.swing.JTextField();
        buscadorTextField3 = new javax.swing.JTextField();
        buscadorJLabel3 = new javax.swing.JLabel();
        btnCrear3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        vendedoresJTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnVendedores.setText("Vendedores");
        btnVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendedoresActionPerformed(evt);
            }
        });

        btnItemsMenu.setText("ItemsMenu");
        btnItemsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemsMenuActionPerformed(evt);
            }
        });

        btnPedidos.setText("Pedidos");
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout seleccionJPanelLayout = new javax.swing.GroupLayout(seleccionJPanel);
        seleccionJPanel.setLayout(seleccionJPanelLayout);
        seleccionJPanelLayout.setHorizontalGroup(
            seleccionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccionJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seleccionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVendedores)
                    .addGroup(seleccionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnPedidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnItemsMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        seleccionJPanelLayout.setVerticalGroup(
            seleccionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccionJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVendedores)
                .addGap(12, 12, 12)
                .addComponent(btnClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnItemsMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPedidos)
                .addContainerGap(396, Short.MAX_VALUE))
        );

        getContentPane().add(seleccionJPanel, java.awt.BorderLayout.LINE_START);

        contenidoJPanel.setLayout(new java.awt.CardLayout());

        VendedorTitleTextField.setBackground(new java.awt.Color(255, 0, 0));
        VendedorTitleTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        VendedorTitleTextField.setText("Lista de Vendedores");
        VendedorTitleTextField.setFocusable(false);
        VendedorTitleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendedorTitleTextFieldActionPerformed(evt);
            }
        });

        buscadorVendedorJLabel.setText("Buscador:");

        btnCrearVendedor.setText("Crear Nuevo Vendedor");
        btnCrearVendedor.setToolTipText("");
        btnCrearVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearVendedorActionPerformed(evt);
            }
        });

        vendedoresJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, ""},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Dirección", "Menú", "Acciones"
            }
        ));
        VendedorJScrollPane.setViewportView(vendedoresJTable);

        javax.swing.GroupLayout ListaVendedoresJPanelLayout = new javax.swing.GroupLayout(ListaVendedoresJPanel);
        ListaVendedoresJPanel.setLayout(ListaVendedoresJPanelLayout);
        ListaVendedoresJPanelLayout.setHorizontalGroup(
            ListaVendedoresJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaVendedoresJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListaVendedoresJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VendedorJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(VendedorTitleTextField)
                    .addGroup(ListaVendedoresJPanelLayout.createSequentialGroup()
                        .addComponent(btnCrearVendedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(buscadorVendedorJLabel)
                        .addGap(18, 18, 18)
                        .addComponent(buscadorVendedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ListaVendedoresJPanelLayout.setVerticalGroup(
            ListaVendedoresJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaVendedoresJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VendedorTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ListaVendedoresJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscadorVendedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscadorVendedorJLabel)
                    .addComponent(btnCrearVendedor))
                .addGap(18, 18, 18)
                .addComponent(VendedorJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout VendedorJPanelLayout = new javax.swing.GroupLayout(VendedorJPanel);
        VendedorJPanel.setLayout(VendedorJPanelLayout);
        VendedorJPanelLayout.setHorizontalGroup(
            VendedorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
            .addGroup(VendedorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(VendedorJPanelLayout.createSequentialGroup()
                    .addGap(0, 77, Short.MAX_VALUE)
                    .addComponent(ListaVendedoresJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 78, Short.MAX_VALUE)))
        );
        VendedorJPanelLayout.setVerticalGroup(
            VendedorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(VendedorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(VendedorJPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ListaVendedoresJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        contenidoJPanel.add(VendedorJPanel, "Vendedor");

        ClienteTitleTextField.setBackground(new java.awt.Color(255, 0, 0));
        ClienteTitleTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ClienteTitleTextField.setText("Lista de Clientes");
        ClienteTitleTextField.setFocusable(false);
        ClienteTitleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteTitleTextFieldActionPerformed(evt);
            }
        });

        buscadorJLabel1.setText("Buscador:");

        btnCrear1.setText("Crear Nuevo Cliente");
        btnCrear1.setToolTipText("");
        btnCrear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrear1ActionPerformed(evt);
            }
        });

        clientesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Dirección", "Cuit", "Direccion", "Pedidos", "Acciones"
            }
        ));
        jScrollPane2.setViewportView(clientesJTable);

        javax.swing.GroupLayout ListaClienteJPanelLayout = new javax.swing.GroupLayout(ListaClienteJPanel);
        ListaClienteJPanel.setLayout(ListaClienteJPanelLayout);
        ListaClienteJPanelLayout.setHorizontalGroup(
            ListaClienteJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaClienteJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListaClienteJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(ClienteTitleTextField)
                    .addGroup(ListaClienteJPanelLayout.createSequentialGroup()
                        .addComponent(btnCrear1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(buscadorJLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(buscadorTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ListaClienteJPanelLayout.setVerticalGroup(
            ListaClienteJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaClienteJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ClienteTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ListaClienteJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscadorTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscadorJLabel1)
                    .addComponent(btnCrear1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout ClienteJPanelLayout = new javax.swing.GroupLayout(ClienteJPanel);
        ClienteJPanel.setLayout(ClienteJPanelLayout);
        ClienteJPanelLayout.setHorizontalGroup(
            ClienteJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
            .addGroup(ClienteJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ClienteJPanelLayout.createSequentialGroup()
                    .addGap(0, 84, Short.MAX_VALUE)
                    .addComponent(ListaClienteJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 85, Short.MAX_VALUE)))
        );
        ClienteJPanelLayout.setVerticalGroup(
            ClienteJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(ClienteJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ClienteJPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ListaClienteJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        contenidoJPanel.add(ClienteJPanel, "Cliente");

        ItemMenuTitleTextField.setBackground(new java.awt.Color(255, 0, 0));
        ItemMenuTitleTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ItemMenuTitleTextField.setText("Lista de ItemsMenu");
        ItemMenuTitleTextField.setFocusable(false);
        ItemMenuTitleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemMenuTitleTextFieldActionPerformed(evt);
            }
        });

        buscadorJLabel2.setText("Buscador:");

        btnCrearItemMenu.setText("Crear Nuevo ItemMenu");
        btnCrearItemMenu.setToolTipText("");
        btnCrearItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearItemMenuActionPerformed(evt);
            }
        });

        vendedoresJTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Descripcion", "Precio", "Categoria", "AptoVegano", "Acciones"
            }
        ));
        jScrollPane3.setViewportView(vendedoresJTable2);

        javax.swing.GroupLayout ListaPedidosPanel2Layout = new javax.swing.GroupLayout(ListaPedidosPanel2);
        ListaPedidosPanel2.setLayout(ListaPedidosPanel2Layout);
        ListaPedidosPanel2Layout.setHorizontalGroup(
            ListaPedidosPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaPedidosPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListaPedidosPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ItemMenuTitleTextField)
                    .addGroup(ListaPedidosPanel2Layout.createSequentialGroup()
                        .addComponent(btnCrearItemMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscadorJLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(buscadorTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ListaPedidosPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ListaPedidosPanel2Layout.setVerticalGroup(
            ListaPedidosPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaPedidosPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ItemMenuTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ListaPedidosPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscadorTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscadorJLabel2)
                    .addComponent(btnCrearItemMenu))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout ItemMenuJPanelLayout = new javax.swing.GroupLayout(ItemMenuJPanel);
        ItemMenuJPanel.setLayout(ItemMenuJPanelLayout);
        ItemMenuJPanelLayout.setHorizontalGroup(
            ItemMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
            .addGroup(ItemMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ItemMenuJPanelLayout.createSequentialGroup()
                    .addGap(0, 40, Short.MAX_VALUE)
                    .addComponent(ListaPedidosPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 40, Short.MAX_VALUE)))
        );
        ItemMenuJPanelLayout.setVerticalGroup(
            ItemMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(ItemMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ItemMenuJPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ListaPedidosPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        contenidoJPanel.add(ItemMenuJPanel, "ItemMenu");

        TitleTextField3.setBackground(new java.awt.Color(255, 0, 0));
        TitleTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TitleTextField3.setText("Lista de Pedidos");
        TitleTextField3.setFocusable(false);
        TitleTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitleTextField3ActionPerformed(evt);
            }
        });

        buscadorJLabel3.setText("Buscador:");

        btnCrear3.setText("Crear Nuevo Vendedor");
        btnCrear3.setToolTipText("");
        btnCrear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrear3ActionPerformed(evt);
            }
        });

        vendedoresJTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cliente", "Vendedor", "Estado", "Acciones"
            }
        ));
        jScrollPane4.setViewportView(vendedoresJTable3);

        javax.swing.GroupLayout ListaPedidosJPanleLayout = new javax.swing.GroupLayout(ListaPedidosJPanle);
        ListaPedidosJPanle.setLayout(ListaPedidosJPanleLayout);
        ListaPedidosJPanleLayout.setHorizontalGroup(
            ListaPedidosJPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaPedidosJPanleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListaPedidosJPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(TitleTextField3)
                    .addGroup(ListaPedidosJPanleLayout.createSequentialGroup()
                        .addComponent(btnCrear3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(buscadorJLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(buscadorTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ListaPedidosJPanleLayout.setVerticalGroup(
            ListaPedidosJPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaPedidosJPanleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ListaPedidosJPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscadorTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscadorJLabel3)
                    .addComponent(btnCrear3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PedidoJPanelLayout = new javax.swing.GroupLayout(PedidoJPanel);
        PedidoJPanel.setLayout(PedidoJPanelLayout);
        PedidoJPanelLayout.setHorizontalGroup(
            PedidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
            .addGroup(PedidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PedidoJPanelLayout.createSequentialGroup()
                    .addGap(0, 77, Short.MAX_VALUE)
                    .addComponent(ListaPedidosJPanle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 78, Short.MAX_VALUE)))
        );
        PedidoJPanelLayout.setVerticalGroup(
            PedidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(PedidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PedidoJPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ListaPedidosJPanle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        contenidoJPanel.add(PedidoJPanel, "Pedido");

        getContentPane().add(contenidoJPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarTabla() {
    // Aquí configuras la columna de botones
    vendedoresJTable.getColumnModel().getColumn(3).setCellRenderer(new ButtonRendererEditor());
    vendedoresJTable.getColumnModel().getColumn(3).setCellEditor(new ButtonRendererEditor());
    }
    
    private void btnVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendedoresActionPerformed
        // TODO add your handling code here:
        CardLayout ly = (CardLayout)contenidoJPanel.getLayout();
        ly.show(contenidoJPanel, "Vendedor");
        
    }//GEN-LAST:event_btnVendedoresActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        CardLayout ly = (CardLayout)contenidoJPanel.getLayout();
        ly.show(contenidoJPanel, "Cliente");
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnItemsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemsMenuActionPerformed
        // TODO add your handling code here:
        CardLayout ly = (CardLayout)contenidoJPanel.getLayout();
        ly.show(contenidoJPanel, "ItemMenu");
    }//GEN-LAST:event_btnItemsMenuActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        // TODO add your handling code here:
        CardLayout ly = (CardLayout)contenidoJPanel.getLayout();
        ly.show(contenidoJPanel, "Pedido");
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void VendedorTitleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendedorTitleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VendedorTitleTextFieldActionPerformed

    private void btnCrearVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearVendedorActionPerformed

    private void ClienteTitleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteTitleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClienteTitleTextFieldActionPerformed

    private void btnCrear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrear1ActionPerformed

    private void ItemMenuTitleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemMenuTitleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemMenuTitleTextFieldActionPerformed

    private void btnCrearItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearItemMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearItemMenuActionPerformed

    private void TitleTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitleTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TitleTextField3ActionPerformed

    private void btnCrear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrear3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrear3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuJFrame().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ClienteJPanel;
    private javax.swing.JTextField ClienteTitleTextField;
    private javax.swing.JPanel ItemMenuJPanel;
    private javax.swing.JTextField ItemMenuTitleTextField;
    private javax.swing.JPanel ListaClienteJPanel;
    private javax.swing.JPanel ListaPedidosJPanle;
    private javax.swing.JPanel ListaPedidosPanel2;
    private javax.swing.JPanel ListaVendedoresJPanel;
    private javax.swing.JPanel PedidoJPanel;
    private javax.swing.JTextField TitleTextField3;
    private javax.swing.JPanel VendedorJPanel;
    private javax.swing.JScrollPane VendedorJScrollPane;
    private javax.swing.JTextField VendedorTitleTextField;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnCrear1;
    private javax.swing.JButton btnCrear3;
    private javax.swing.JButton btnCrearItemMenu;
    private javax.swing.JButton btnCrearVendedor;
    private javax.swing.JButton btnItemsMenu;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnVendedores;
    private javax.swing.JLabel buscadorJLabel1;
    private javax.swing.JLabel buscadorJLabel2;
    private javax.swing.JLabel buscadorJLabel3;
    private javax.swing.JTextField buscadorTextField1;
    private javax.swing.JTextField buscadorTextField2;
    private javax.swing.JTextField buscadorTextField3;
    private javax.swing.JLabel buscadorVendedorJLabel;
    private javax.swing.JTextField buscadorVendedorTextField;
    private javax.swing.JTable clientesJTable;
    private javax.swing.JPanel contenidoJPanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel seleccionJPanel;
    private javax.swing.JTable vendedoresJTable;
    private javax.swing.JTable vendedoresJTable2;
    private javax.swing.JTable vendedoresJTable3;
    // End of variables declaration//GEN-END:variables
}
