/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package isi.deso.tpdsw.Views;

import java.awt.CardLayout;
import javax.swing.*;
/**
 *
 * @author santi
 */
public class MenuJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuJFrame
     */
    public MenuJFrame() {
        initComponents();
        configurarLayout();
        configurarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionJPanel = new javax.swing.JPanel();
        btnClientes = new javax.swing.JButton();
        btnVendedores = new javax.swing.JButton();
        btnItemsMenu = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        contenidoJPanel = new javax.swing.JPanel();
        defaultJPanel = new javax.swing.JPanel();
        etiqueta = new javax.swing.JLabel();
        fillerWest = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        fillerEast = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnVendedores.setText("Vendedores");
        btnVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendedoresActionPerformed(evt);
            }
        });

        btnItemsMenu.setText("ItemsMenu");
        btnItemsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemsMenuActionPerformed(evt);
            }
        });

        btnPedidos.setText("Pedidos");
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout seleccionJPanelLayout = new javax.swing.GroupLayout(seleccionJPanel);
        seleccionJPanel.setLayout(seleccionJPanelLayout);
        seleccionJPanelLayout.setHorizontalGroup(
            seleccionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccionJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seleccionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVendedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnItemsMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        seleccionJPanelLayout.setVerticalGroup(
            seleccionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccionJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVendedores)
                .addGap(12, 12, 12)
                .addComponent(btnClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnItemsMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPedidos)
                .addContainerGap(396, Short.MAX_VALUE))
        );

        getContentPane().add(seleccionJPanel, java.awt.BorderLayout.LINE_START);

        contenidoJPanel.setLayout(new java.awt.CardLayout());

        defaultJPanel.setLayout(new java.awt.BorderLayout());

        etiqueta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        etiqueta.setForeground(new java.awt.Color(102, 102, 102));
        etiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta.setText("Seleccione la entidad con la que quiere trabajar");
        etiqueta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        defaultJPanel.add(etiqueta, java.awt.BorderLayout.CENTER);
        defaultJPanel.add(fillerWest, java.awt.BorderLayout.WEST);
        defaultJPanel.add(fillerEast, java.awt.BorderLayout.EAST);

        contenidoJPanel.add(defaultJPanel, "card2");

        getContentPane().add(contenidoJPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarLayout(){
        CardLayout ly = (CardLayout)contenidoJPanel.getLayout();
        contenidoJPanel.add(vendedorJPanel);
        contenidoJPanel.add(clienteJPanel);
        contenidoJPanel.add(itemMenuJPanel);
        contenidoJPanel.add(pedidoJPanel);
        ly.addLayoutComponent(vendedorJPanel, "vendedor");
        ly.addLayoutComponent(clienteJPanel, "cliente");
        ly.addLayoutComponent(itemMenuJPanel, "itemMenu");
        ly.addLayoutComponent(pedidoJPanel, "pedido");
    }
    
    private void configurarTabla() {
    // Aquí configuras la columna de botones
    vendedorJPanel.getJTable().getColumnModel().getColumn(4).setCellRenderer(new ButtonRendererEditor());
    vendedorJPanel.getJTable().getColumnModel().getColumn(4).setCellEditor(new ButtonRendererEditor());
    clienteJPanel.getJTable().getColumnModel().getColumn(5).setCellRenderer(new ButtonRendererEditor());
    clienteJPanel.getJTable().getColumnModel().getColumn(5).setCellEditor(new ButtonRendererEditor());
    itemMenuJPanel.getJTable().getColumnModel().getColumn(5).setCellRenderer(new ButtonRendererEditor());
    itemMenuJPanel.getJTable().getColumnModel().getColumn(5).setCellEditor(new ButtonRendererEditor());
    pedidoJPanel.getJTable().getColumnModel().getColumn(3).setCellRenderer(new ButtonRendererEditor());
    pedidoJPanel.getJTable().getColumnModel().getColumn(3).setCellEditor(new ButtonRendererEditor());
    } 
    
    private void btnVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendedoresActionPerformed
        // TODO add your handling code here:
        CardLayout ly = (CardLayout)contenidoJPanel.getLayout();
        ly.show(contenidoJPanel, "vendedor");
        
    }//GEN-LAST:event_btnVendedoresActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        CardLayout ly = (CardLayout)contenidoJPanel.getLayout();
        ly.show(contenidoJPanel, "cliente");
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnItemsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemsMenuActionPerformed
        // TODO add your handling code here:
        CardLayout ly = (CardLayout)contenidoJPanel.getLayout();
        ly.show(contenidoJPanel, "itemMenu");
    }//GEN-LAST:event_btnItemsMenuActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        // TODO add your handling code here:
        CardLayout ly = (CardLayout)contenidoJPanel.getLayout();
        ly.show(contenidoJPanel, "pedido");
    }//GEN-LAST:event_btnPedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuJFrame().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnItemsMenu;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnVendedores;
    private javax.swing.JPanel contenidoJPanel;
    private javax.swing.JPanel defaultJPanel;
    private javax.swing.JLabel etiqueta;
    private javax.swing.Box.Filler fillerEast;
    private javax.swing.Box.Filler fillerWest;
    private javax.swing.JPanel seleccionJPanel;
    // End of variables declaration//GEN-END:variables
    private VendedoresJPanel vendedorJPanel = new VendedoresJPanel();
    private ClientesJPanel clienteJPanel = new ClientesJPanel();
    private ItemsMenuJPanel itemMenuJPanel = new ItemsMenuJPanel();
    private PedidosJPanel pedidoJPanel = new PedidosJPanel();
    
}
