/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package isi.deso.tpdsw.Views;

import javax.swing.JTable;

/**
 *
 * @author kevin
 */
public class PedidoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PedidoJPanel
     */
    public PedidoJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PedidoJPanel = new javax.swing.JPanel();
        ListaPedidosJPanle = new javax.swing.JPanel();
        TitleTextField3 = new javax.swing.JTextField();
        buscadorTextField3 = new javax.swing.JTextField();
        buscadorJLabel3 = new javax.swing.JLabel();
        btnCrear3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        pedidosJTable = new javax.swing.JTable();

        TitleTextField3.setBackground(new java.awt.Color(255, 0, 0));
        TitleTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TitleTextField3.setText("Lista de Pedidos");
        TitleTextField3.setFocusable(false);
        TitleTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitleTextField3ActionPerformed(evt);
            }
        });

        buscadorJLabel3.setText("Buscador:");

        btnCrear3.setText("Crear Nuevo Vendedor");
        btnCrear3.setToolTipText("");
        btnCrear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrear3ActionPerformed(evt);
            }
        });

        pedidosJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cliente", "Vendedor", "Estado", "Acciones"
            }
        ));
        pedidosJTable.setRowHeight(30);
        jScrollPane4.setViewportView(pedidosJTable);

        javax.swing.GroupLayout ListaPedidosJPanleLayout = new javax.swing.GroupLayout(ListaPedidosJPanle);
        ListaPedidosJPanle.setLayout(ListaPedidosJPanleLayout);
        ListaPedidosJPanleLayout.setHorizontalGroup(
            ListaPedidosJPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListaPedidosJPanleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListaPedidosJPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
                    .addComponent(TitleTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ListaPedidosJPanleLayout.createSequentialGroup()
                        .addComponent(btnCrear3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 532, Short.MAX_VALUE)
                        .addComponent(buscadorJLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(buscadorTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ListaPedidosJPanleLayout.setVerticalGroup(
            ListaPedidosJPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaPedidosJPanleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ListaPedidosJPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscadorTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscadorJLabel3)
                    .addComponent(btnCrear3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PedidoJPanelLayout = new javax.swing.GroupLayout(PedidoJPanel);
        PedidoJPanel.setLayout(PedidoJPanelLayout);
        PedidoJPanelLayout.setHorizontalGroup(
            PedidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 914, Short.MAX_VALUE)
            .addGroup(PedidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ListaPedidosJPanle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PedidoJPanelLayout.setVerticalGroup(
            PedidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGroup(PedidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PedidoJPanelLayout.createSequentialGroup()
                    .addComponent(ListaPedidosJPanle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 914, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PedidoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PedidoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TitleTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitleTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TitleTextField3ActionPerformed

    private void btnCrear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrear3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrear3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ListaPedidosJPanle;
    private javax.swing.JPanel PedidoJPanel;
    private javax.swing.JTextField TitleTextField3;
    private javax.swing.JButton btnCrear3;
    private javax.swing.JLabel buscadorJLabel3;
    private javax.swing.JTextField buscadorTextField3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable pedidosJTable;
    // End of variables declaration//GEN-END:variables
    public JTable getJTable(){
        return this.pedidosJTable;
    }
}
